name: Build Production

on:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FAUCET_URL: ${{ secrets.FAUCET_URL }}
      FAUCET_K: ${{ secrets.FAUCET_K }}

    name: build-prod

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'

      - run: yarn install
      
      - name: Build production
        run: yarn build

      - name: Archive firefox production zip file
        uses: actions/upload-artifact@v2
        with:
          name: firefox.xpi
          path: dist/production/firefox.xpi

      - name: Archive chrome production zip file
        uses: actions/upload-artifact@v2
        with:
          name: chrome.zip
          path: dist/production/chrome.zip

      - name: Archive opera production zip file
        uses: actions/upload-artifact@v2
        with:
          name: opera.crx
          path: dist/production/opera.crx
          
  release-firefox-nightly:
    runs-on: ubuntu-latest
    env:
      FILE: 'firefox.xpi'
      AWS_REGION: 'eu-central-1'
      S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
      S3_KEY: 'elbee-firefox.xpi'
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    name: release-firefox-nightly
    steps:
      - name: Download firefox.xpi
        uses: actions/download-artifact@v2
        with:
          name: firefox.xpi
      - name: Upload releases to S3
        uses: zdurham/s3-upload-github-action@master
        with:
          args: --acl public-read
