name: Build nightlies

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest

    name: build-prod
    env:
      ALBY_API_URL: "https://getalby.com/api"

    permissions:
      issues: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "yarn"

      - run: yarn install

      - name: Build production
        run: yarn build

      - name: Archive firefox production zip file
        uses: actions/upload-artifact@v3
        with:
          name: firefox.xpi
          path: dist/production/firefox.xpi

      - name: Archive chrome production zip file
        uses: actions/upload-artifact@v3
        with:
          name: chrome.zip
          path: dist/production/chrome.zip

      - name: Archive opera production zip file
        uses: actions/upload-artifact@v3
        with:
          name: opera.crx
          path: dist/production/opera.crx
